### ISSUE TITLE
init callback must be a function

### ISSUE THREAD

**Issue by ghost** [Newstex/express-appenlight#1]
Thanks for this great middleware!

It was working great. I recently cleaned my local copy of the repo and installed the `npm` modules again. Now, I seem to be getting this error -

```
TypeError: init callback must be a function
    at TypeError (native)
    at asyncWrapper (/App/node_modules/express-appenlight/stats/async-wrap.js:39:12)
    at Object.<anonymous> (/App/node_modules/express-appenlight/stats/index.js:11:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/App/node_modules/express-appenlight/index.js:14:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

All I'm doing is just this -

`AppEnlight = require('express-appenlight')`

Am I missing something?

**Comment by kopertop** [comment]
Unfortunately it looks like something changed pretty drastically between Node 4.x and Node 6.x. Currently this only works for Node 4.x because of it's dependencies on async-wrap

See: http://blog.trevnorris.com/2015/02/asyncwrap-tutorial-introduction.html

and: https://github.com/nodejs/diagnostics/tree/master/tracing/AsyncWrap

I'm stuck in Node 4.x land because that's all that AWS Lambda can use, but I'm certainly open to pull requests if you find a way to make this work for both 6.x and 4.x environments!

**Comment by kopertop** [comment]
Can you try with the latest develop branch (commit c78c0a989d6ef5dbbad9a3dfa9bad3813fd91a99) and see if it works for you in Node 6+?

**Comment by ghost** [comment]
Hi Chris,

Yes. It seems to work now. I'm on Node 6.9.1, just FYI
